"""empty message

Revision ID: b1af7b4d29de
Revises: a0ada75cd3cd
Create Date: 2020-03-20 14:59:54.261860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b1af7b4d29de'
down_revision = 'a0ada75cd3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'genres')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('genres', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
